dataset:
  name: co3d
  subset: car1
  root_dir: data/CO3D subsets/car1
  annotations_file: data/CO3D subsets/car1/frame_annotations.jgz

prediction:
  point_cloud_path: results/pipeline A/car1/car1.ply
  images_txt: results/pipeline A/car1/images.txt
  cameras_txt: results/pipeline A/car1/cameras.txt

evaluation:
  output_dir: results/pipeline A/car1/metrics_eval
  debug_frame: frame000059.jpg

  voxel_size: 0.01
  point_radius_px: 1
  dilate_kernel: 3
  dilate_iterations: 1

  compute_mask_iou: true
  compute_depth_mae: true

  save_debug_images: true
  max_frames: null