data:
  images_path: data/CO3D subsets/teddy1/images
  masked_images_path: data/masked_images/masked
colmap:
  executable: C:/COLMAP-3.7-windows-cuda/bin/colmap.exe
  database_path: data/colmap_workspace/database.db
  sparse_path: data/colmap_workspace/sparse
  dense_path: data/colmap_workspace/dense
  fused_path: data/colmap_workspace/dense/fused.ply